gen_data['main'] = [
    'Se ha informado de {suceso} durante {momento}.',
    'Hay rumores de {suceso}.',
    'Han surgido noticias de {suceso} durante {momento}.',
    'Los vecinos de la zona comentan acerca de {suceso}.'
  ];

  gen_data['suceso'] = [
    'extrañas luces',
    'desapariciones de {victima}',
    'extraños ruidos',
    'ruidos grotescos',
    'multituz de cadaveres destrozados de {victima}',
    'un avistamiento de un posible {criatura}',
    'un ataque de un posible {criatura}',
    'una serie de asesinatos por parte de un supuesto {criatura}',
    'una serie de asesinatos por parte de un supuesto {criatura}',
    'una serie de asesinatos por parte de un supuesto {criatura}',
    'una serie de asesinatos por parte de un supuesto {criatura}',
    'un cadaver de {animales} cada dia cada {evento}',
  ];
  gen_data['victima'] = {
    '1-3': 'civiles mundanos',
    '4-5': 'campesinos',
    '6-7': 'niños',
      '8': 'ganado',
      '9': 'vacas',
      '10': 'arboles',
      '11': 'masas de agua',
      '12': 'hadas',
      '13': 'mujeres',
      '14': 'personas',
      '15': 'pueblerinos',
      '15': 'pajaros',
      '15': 'grandes masas de insectos'
  };

  gen_data['momento'] = [
    'los ultmos dias',
    'las ulmas noches',
    'en las ultimas noches',
    'las ultimas semanas',
    'cada {evento}',
    'todos los {diaSemana} durante los utimos meses',
    'todos los {diaSemana} durante las utimas semanas',
  ];
  gen_data['evento'] = [
    'luna llena',
    'cuarto menguante',
    'cuarto creciente',
    'luna nueva',
    'pocas semanas',
    'pocos meses',
  ];
  
  gen_data['diaSemana'] = [
    'lunes',
    'martes',
    'miercoles',
    'jueves',
    'viernes',
    'sabado',
    'domingo'
  ];

  gen_data['animales'] = [
    "Caballo de monta",
    "Caballo de tiro",
    "Alce",
    "Serpiente venenosa",
    "Mastín",
    "Mula",
    "Noble",
    "Poni",
    "Guardia",
    "Lagarto",
    "Lémur",
    "Murciélago",
    "Piraña",
    "Plebeyo",
    "Pulpo",
    "Rana",
    "Rata",
    "Tejón",
    "Bandido",
    "Camello",
    "Cangrejo gigante",
    "Escorpión",
    "Gato",
    "Halcón",
    "Hiena",
    "Arbusto consciente",
    "Babuino",
    "Búho",
    "Buitre",
    "Caballito de mar",
    "Cabra",
    "Cangrejo",
    "Chacal",
    "Ciervo",
    "Comadreja",
    "Cuervo",
    "Águila",
    "Araña",
    "Jabalí",
    "Lagarto gigante",
    "Lobo",
    "Méfit de vapor",
    "Murciélago gigante",
    "Pantera"
  ];


  gen_data['criatura'] = [
    'Shantaks',
    'sectario',
    'horrendo cazador',
    "Arbusto consciente",
    "Escarabajo de fuego gigante",
    "Homúnculo",
    "Hongo chillón",
    "Comadreja gigante",
    "Estirge",
    "Guerrero tribal",
    "Halcón sangriento",
    "Kóbold",
    "Rata gigante",
    "Rata gigante enferma",
    "Sectario",
    "Serpiente voladora",
    "Sirénido",
    "Acólito",
    "Araña lobo gigante",
    "Búho gigante",
    "Ciempiés gigante",
    "Drow",
    "Duende",
    "gran enjambre de cuervos",
    "gran enjambre de murciélagos",
    "gran enjambre de ratas",
    "Espada voladora",
    "Esqueleto",
    "Gibado",
    "Goblin",
    "Grimórlock",
    "Hachapico",
    "Hongo violáceo",
    "Lagarto gigante",
    "Méfit de vapor",
    "Murciélago gigante",
    "Perro intermitente",
    "Pseudodragón",
    "Rana gigante",
    "Serpiente constrictora",
    "Serpiente venenosa gigante",
    "Tejón gigante",
    "Zombi",
    "Avispa gigante",
    "Caballito de mar gigante",
    "Caballo de guerra",
    "Cabra gigante",
    "Cieno gris",
    "Cocatriz",
    "Cocodrilo",
    "Enjambre de insectos",
    "Esqueleto de caballo de guerra",
    "Explorador",
    "Gnoll",
    "Gnomo de las profundidades (svirfneblin)",
    "Gran goblin",
    "Hombre lagarto",
    "Huargo",
    "Magmino",
    "Mantoscuro",
    "Matón",
    "Méfit de hielo",
    "Méfit de magma",
    "Méfit de polvo",
    "Monstruo corrosivo",
    "Orco",
    "Oso negro",
    "Sajuaguín",
    "Sátiro",
    "Simio",
    "Sombra",
    "Tiburón de arrecife",
    "Águila gigante",
    "Araña gigante",
    "Armadura animada",
    "Arpía",
    "Buitre gigante",
    "Diablillo",
    "Dragón de cobre sierpe",
    "Dragón de oropel sierpe",
    "Dríada",
    "Duérgar",
    "Enjambre de pirañas",
    "Espectro",
    "Espía",
    "Hiena gigante",
    "Hipogrifo",
    "León",
    "Lobo terrible",
    "Necrófago (Gul)",
    "Osgo",
    "Oso pardo",
    "Perro de la muerte",
    "Pulpo gigante",
    "Quasit",
    "Sapo gigante",
    "Tigre",
    "Alce gigante",
    "Alfombra de asfixiar",
    "Ankheg",
    "Árbol consciente",
    "Azer",
    "Berserker",
    "Bocón barbotante",
    "Capitán bandido",
    "Centauro",
    "Cubo gelatinoso",
    "Dragón blanco sierpe",
    "Dragón de bronce sierpe",
    "Dragón de plata sierpe",
    "Dragón negro sierpe",
    "Dragón verde sierpe",
    "Druida",
    "Enjambre de serpientes venenosas",
    "Esqueleto de minotauro",
    "Fanático de una secta",
    "Fuego fatuo",
    "Gárgola",
    "Gelatina ocre",
    "Gric",
    "Grifo",
    "Hombre rata",
    "Jabalí gigante",
    "Mimeto",
    "Necrario (Ghast)",
    "Ogro",
    "Ogro zombi",
    "Oso polar",
    "Pegaso",
    "Plesiosaurus",
    "Rinoceronte",
    "Sacerdote",
    "Saga marina",
    "Serpiente constrictora gigante",
    "Sirenio",
    "Tiburón cazador",
    "Tigre dientes de sable",
    "Trácnido",
    "Araña de fase",
    "Ballena asesina",
    "Basilisco",
    "Caballero",
    "Can del infierno",
    "Diablo barbado",
    "Doppelgánger",
    "Dragón azul sierpe",
    "Dragón de oro sierpe",
    "Escorpión gigante",
    "Hombre lobo",
    "Lobo de invierno",
    "Mantícora",
    "Minotauro",
    "Momia",
    "Oso lechuza",
    "Pesadilla",
    "Saga cetrina",
    "Tumulario",
    "Veterano",
    "Couatl",
    "Dragón rojo sierpe",
    "Elefante",
    "Ettin",
    "Fantasma",
    "Hombre jabalí",
    "Hombre tigre",
    "Khuul",
    "Lamia",
    "Pudin negro",
    "Súcubo/íncubo",
    "Broza movediza",
    "Bulete",
    "Cocodrilo gigante",
    "Diablo punzante",
    "Elemental de agua",
    "Elemental de aire",
    "Elemental de fuego",
    "Elemental de tierra",
    "Engendro vampírico",
    "Gigante de las colinas",
    "Gladiador",
    "Gólem de carne",
    "Gorgón",
    "Hombre oso",
    "Incorpóreo",
    "Morfolito",
    "Otyugh",
    "Saga nocturna",
    "Salamandra",
    "Semidragón rojo veterano",
    "Tiburón gigante",
    "Triceratops",
    "Troll",
    "Unicornio",
    "Xorn",
    "Acechador invisible",
    "Draco",
    "Dragón blanco joven",
    "Dragón de oropel joven",
    "Draña",
    "Mago",
    "Mamut",
    "Medusa",
    "Quimera",
    "Vrock",
    "Dragón de bronce joven",
    "Dragón negro joven",
    "Gigante de piedra",
    "Guardián escudo",
    "Oni",
    "Simio gigante",
    "Asesino",
    "Diablo de la cadena",
    "Dragón verde joven",
    "Gigante de escarcha",
    "Hezrou",
    "Hidra",
    "Manto",
    "Naga espiritual",
    "Tyrannosaurus rex",
    "Diablo óseo",
    "Dragón azul joven",
    "Dragón de plata joven",
    "Ent",
    "Gigante de fuego",
    "Gigante de las nubes",
    "Glabrezu",
    "Gólem de arcilla",
    "Abolez",
    "Deva",
    "Dragón de oro joven",
    "Dragón rojo joven",
    "Gólem de piedra",
    "Naga guardiana",
    "Behir",
    "Diablo astado",
    "Djinni",
    "Ginoesfinge",
    "Ifriti",
    "Remorhaz",
    "Roc",
    "Archimago",
    "Erinia",
    "Dragón blanco adulto",
    "Dragón de oropel adulto",
    "Gigante de la tormenta",
    "Nálfeshnee",
    "Rakshasa",
    "Vampiro",
    "Diablo gélido",
    "Dragón de cobre adulto",
    "Dragón negro adulto",
    "Dragón de bronce adulto",
    "Dragón verde adulto",
    "Gusano púrpura",
    "Señor de las momias",
    "Dragón azul adulto",
    "Dragón de plata adulto",
    "Gólem de hierro",
    "Marilith",
    "Planotáreo",
    "Androesfinge",
    "Dragón de oro adulto",
    "Dragón rojo adulto",
    "Dragón tortuga",
    "Bálor",
    "Diablo de la sima",
    "Dragón blanco antiguo",
    "Dragón de cobre antiguo",
    "Dragón negro antiguo",
    "Liche",
    "Solar",
    "Dragón de bronce antiguo",
    "Dragón verde antiguo",
    "Dragón azul antiguo",
    "Dragón de plata antiguo",
    "Kraken",
    "Dragón de oro antiguo",
    "Dragón rojo antiguo",
    "Tarasca"
]